spring:
  application:
    name: "demo.webflux.users"
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:postgresql://${APP_DB_URL}/${APP_DB_NAME}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
logging:
  level:
    com.jpdr.apps.demo.webflux: ${APP_LOG_LEVEL}
    org.springframework.r2dbc: ${APP_LOG_LEVEL}
app:
  pod-name: ${APP_POD_NAME}
  event-logger:
    kafka:
      enabled: ${APP_EVENT_LOGGER_KAFKA_ENABLED}
      topic: ${APP_EVENT_LOGGER_KAFKA_TOPIC}
      boostrap-server: ${APP_EVENT_LOGGER_KAFKA_BOOSTRAP_SERVER}
      compression-type: ${APP_EVENT_LOGGER_KAFKA_COMPRESSION_TYPE}
      delivery-timeout-ms: ${APP_EVENT_LOGGER_KAFKA_DELIVERY_TIMEOUT_MS}
      request-timeout-ms: ${APP_EVENT_LOGGER_KAFKA_REQUEST_TIMEOUT_MS}
      add-type-info-headers: ${APP_EVENT_LOGGER_KAFKA_ADD_TYPE_INFO_HEADERS};
      retries: ${APP_EVENT_LOGGER_KAFKA_RETRIES}
